---
title: "SLR_COEFFS"
author: "Mengxue Zhang"
date: "2023-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(bench)
```

To use the fucntion 'simple_linear_regression_coeffs':

```{r}
# example 1
df1 <- data.frame(x = c(1, 2, 3, 4, 5),
                 y = c(1, 5, 8, 15, 26))

# implemented function
out1 = simple_linear_regression_coeffs(df1, x = df1$x, y = df1$y)

# original R function lm()
model1 = lm(y ~ x, data = df1)
summary(model1)

# comparison
# correctness
all.equal(out1[1, 1], summary(model1)$coefficients["(Intercept)","Estimate"])
all.equal(out1[2, 1], summary(model1)$coefficients["x","Estimate"])

# efficiency
system.time(simple_linear_regression_coeffs(df1, x = df1$x, y = df1$y))
system.time(lm(y ~ x, data = df1))


# example 2
# Source of data: https://www.datacamp.com/tutorial/linear-regression-R
ageandheight <- read_excel("../ageandheight.xls", sheet = "Hoja2")

# implemented function
out2 = simple_linear_regression_coeffs(ageandheight, x = ageandheight$age,
                                       y = ageandheight$height)

# original R function lm()
lmHeight = lm(height ~ age, data = ageandheight)
summary(lmHeight)

# comparison
# correctness
all.equal(out2[1, 1], summary(lmHeight)$coefficients["(Intercept)","Estimate"])
all.equal(out2[2, 1], summary(lmHeight)$coefficients["age","Estimate"])

# efficiency
system.time(simple_linear_regression_coeffs(ageandheight, x = ageandheight$age, y = ageandheight$height))
system.time(lm(height ~ age, data = ageandheight))
```

